### ISSUE TITLE
Last command in multi-command query not executed

### ISSUE THREAD

**Issue by alasdairdc** [dbcli/mycli#163]
When multi_line is set to true and pasting, e.g.:

``` sql
use mysql;
select User from user;
```

The last command is not executed.

The command pastes on a single line with the semi colon delimiter but the last command is not executed, pasting:

``` sql
use mysql;
select User from user;
select User from user;
```

only returns one resultset from the user query.

EDIT:  This is on version 1.4.0 on Debian Jessie.

**Comment by amjith** [comment]
Yup. This is a bug. It's not even multi-line mode, even without the multi-line mode, it only runs the first command. I think it's because the enter key is interpreted as end of a query and then it runs the query but the second query is abandoned.

I'll see what I can do about this bug.

**Comment by amjith** [comment]
@jonathanslenders Can I get some help on this one? I added a `pdb` statement on this line to examine the incoming `document.text` and it only sends me the first statement (`use mysql;`) from this snippet: 

```
use mysql;
select User from user;
```

But I checked the behavior on ptpython and pasting multiple lines works as expected. So I'm not sure why it is different on mycli and pgcli.

**Comment by tsroten** [comment]
This is interesting that you both see this as a bug. Personally, I see this as the desired behavior. Moreover, the `mysql` command-line utility functions this way. So do the PHP and Python command-line interpreters.

I see a common-use case like this: User has a multi-line query they want to paste, then modify, then run. This is how I run a lot of queries.

What you're proposing is adding a character to the user's command (newline character). The user didn't actually submit that final newline character.

**Comment by amjith** [comment]
Maybe there is a misunderstanding. What I see happening is the first query `use mysql;` runs, the second query shows up in the prompt but it is not executed and neither can I press enter to run it.

Can you confirm that this is the behavior you're seeing?

**Comment by tsroten** [comment]
Oh, feel free to ignore me. I had multiline turned off. I see the bug now. Yes, that definitely should be fixed :). @alasdairdc Thanks for reporting that!

**Comment by tsroten** [comment]
@amjith I'm trying to hunt this bug down. It has something to do with the way that mycli/ptpython handle the newline/enter keybinding. You can see that ptpython has [quite a bit of logic for that key](https://github.com/jonathanslenders/ptpython/blob/cf8350904a824297d480c8c4d6be9f32e8d66121/ptpython/key_bindings.py#L95-L130).

**Comment by tsroten** [comment]
Okay, so I'm not sure how to fix it, but in the first example above with two statements, the first newline triggers a keybinding event for that first statement only. It's processed. The next statement doesn't trigger an event because there is no newline after it. That's fine, that's how it should be. The problem is that the statement is not pasted onto the next prompt (this is how ptpython and mysql work) -- instead, it is pasted with the first statement, so there is no way to run it.

In the second example, the same thing happens, except there are two newlines, so there are two Ctrl-J (newline) events -- hence, two commands are run. The last one isn't run because there is no newline after it.

So, I'm unsure how ptpython automatically pushes the next statement to a new prompt when a newline is encountered.

@jonathanslenders Any ideas?

**Comment by jonathanslenders** [comment]
Sorry about the late reply, I forgot about this issue. Today I don't have much time, but tomorrow I'll have a look. Don't spend too much time looking for it. Jonathan

**Comment by tsroten** [comment]
@jonathanslenders Any ideas on this one?

**Comment by dbolser-ebi** [comment]
bump

**Comment by tsroten** [comment]
I'm closing this as it looks like it is fixed.

When I paste and run:
```mysql
select 1;
select 2;
select 3;
```

I get:
```
+-----+
|   1 |
|-----|
|   1 |
+-----+
1 row in set
+-----+
|   2 |
|-----|
|   2 |
+-----+
1 row in set
+-----+
|   3 |
|-----|
|   3 |
+-----+
1 row in set
```

**Comment by dbolser-ebi** [comment]
Hmm... I'm still seeing just '|   1 |' when under screen... I suspect this is a screen bug, not a mycil bug.

**Comment by dbolser-ebi** [comment]
Here is my screen cap of what happens without screen, pasting the following, with or without Multiline

    use mysql;
    select User from user;
    select User from user;
    

## Sorry for the 'real time' capture:
https://asciinema.org/a/e6ngrwsjx1ruvfjt40aczsnx9

You can see that I have to manually press return despite pasting a newline, and that the autocomplete box pops up annoyingly.

**Comment by tsroten** [comment]
@dbolser-ebi No problem with the real-time capture :)

The final newline is pasted, so it's not going to trigger the query to submit. As far as I can tell, this is [by design](https://cirw.in/blog/bracketed-paste) in prompt toolkit.

The autocomplete box pops up because of the final newline -- it's like typing a space after `select` -- you'll get suggestions for your next word.

If you paste without a final newline, you should not see the autocomplete box:
```sql
select 1;
select 2;
select 3;
```

**Comment by dbolser-ebi** [comment]
Hmm... in multi-line mode I'd expect the queries to be executed one by one following each newline after each ; 

That's just my expectation, not necessarily the right thing ;-)

**Comment by dbolser-ebi** [comment]
Also, what's with the formatting? It's turning my SQL into concrete poetry!
`http://pasteboard.co/50bvYNKVk.png`

**Comment by amjith** [comment]
> Also, what's with the formatting? It's turning my SQL into concrete poetry!

@dbolser-ebi Congratulations!! You've unlocked our secret poetry formatting mode. We love this format, I wish more people would use it. 

If you don't like it, I understand, it's not everyone's cup of tea. Here's how you can turn this off  press Ctrl+Alt+Delete+Esc+ScrollLock+Space. Oh you need to be suspended upside down and sipping a cup of oolong tea and singing "La donna è mobile" while pressing the key. 😛 

I hope you know I'm totally kidding. That looks like a ridiculous bug. What version of mycli are you using? I just tried this on 1.10.0 and I can't reproduce the poetry.

**Comment by j-bennet** [comment]
@amjith From the pasteboard above it looks like @dbolser-ebi is using 1.10.0.

**Comment by j-bennet** [comment]
But it may be a different prompt toolkit than you have @amjith. @dbolser-ebi , can you post the `pip freeze` output?

**Comment by dbolser-ebi** [comment]
To be clear, this is when I paste the following SQL from emacs into mycli running under screen with Multiline: ON

```
SELECT
  x.*,
  ROUND(DONE/N*100) AS pct_done,
  READY*runtime_sec/60/60 AS hours
FROM (
  SELECT
    ppp.job_id, ppp.input_id,
    COUNT(*) AS N,
    SUM(IF(c.status='READY',   1, 0)) AS READY,
    SUM(IF(c.status='RUN',     1, 0)) AS RUN,
    SUM(IF(c.status='CLAIMED', 1, 0)) AS CLAIMED,
    SUM(IF(c.status='DONE',    1, 0)) AS DONE,
    SUM(IF(c.status='FAILED',  1, 0)) AS FAILED,
    AVG(IF(c.status='DONE',
      c.runtime_msec, NULL))/1000    AS runtime_sec 
  FROM job  c
  INNER JOIN job   p ON  c.prev_job_id =   p.job_id
  INNER JOIN job  pp ON  p.prev_job_id =  pp.job_id
  INNER JOIN job ppp ON pp.prev_job_id = ppp.job_id
  WHERE c.analysis_id = 232
  GROUP BY 1
  WITH ROLLUP
) AS
  x
;
```

As for the prompt toolkit version, one potentially complicating factor is that I'm in the habit of running mycli directly, without first invoking the virtualenv that I used to install it. i.e.
`/homes/dbolser/EG_Places/External/mycli-master/venv/bin/mycli`

where the virtualenv is under `venv/`

for this reason pip freeze gives me:
https://gist.github.com/dbolser-ebi/fc32111dd4be1d990220fe366d7a241e

when I actually activate the venv I get:
```
(venv) [dbolser@ebi-cli-002 mycli-master]$ pip freeze
click==6.7
configobj==5.0.6
mycli==1.10.0
prompt-toolkit==1.0.14
pycrypto==2.6.1
pycryptodome==3.4.5
Pygments==2.2.0
PyMySQL==0.7.11
six==1.10.0
sqlparse==0.2.3
wcwidth==0.1.7
yolk3k==0.9
```

So I /guess/ I'm using prompt-toolkit 1.0.14?

I think so, because I see exactly the same error under screen when running mycli after properly activating the environment.

Screen is it's own special beast, I think it's messing with termcap for it's own reasons.

**Comment by alasdairdc** [comment]
Does the same happen if you try it witihn [tmux](https://tmux.github.io/)?

**Comment by jonathanslenders** [comment]
Which terminal application are you using? Does it support bracketed paste?

**Comment by alasdairdc** [comment]
can confirm multi-command queries work correctly in `1.8.1-2`

```
mysql root@localhost:mysql> select 1;
                         -> select 2;
                         -> select 3;
+-----+
|   1 |
|-----|
|   1 |
+-----+
1 row in set
+-----+
|   2 |
|-----|
|   2 |
+-----+
1 row in set
+-----+
|   3 |
|-----|
|   3 |
+-----+
1 row in set
Time: 0.003s
mysql root@localhost:mysql>
```

with the footer 

```
 [F2] Smart Completion: ON  [F3] Multiline: ON   (Semi-colon [;] will end the line)[F4] Emacs-mode 
```

I think as @dbolser-ebi suggested 

> Screen is it's own special beast, I think it's messing with termcap for it's own reasons.

the same also applies to tmux being a special beast.
